import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { signIn, signOut, useSession } from 'next-auth/client'

export default function Home() {

  const [session, loading] = useSession()

  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>




    </div >
  )
}
